compile_wr:
	gcc writer.c -o writer
compile_rd:
	gcc reader.c -o reader
run_wr:
	./writer writer.c
run_rd:
	./reader
run_wr_1:
	./writer one
run_wr_2:
	./writer two
run_wr_3:
	./writer three
run_wr_easy:
	./writer easy